* TASKS

** TODO switch to modalka

** TODO implement convinient isearch

** TODO bind rect selection

** TODO get rid of annoying quirks
   - map russian characters
   - map capital charactes (?)
   - add more convinient bindings that exit modal state properly
   - all unused single-key presses are nil 

** DONE examine xah-fly-keys and steal good functions
     
* IDEAS
  
** object manipulation 
   A sequence "special-key char" selects an object type when in modal mode, where _char_ is the first letter of text object name.

   If avy is used to navigate to anywhere and mark-state is not nil, then expand region according to symbol in mark-state. _USE ADVICE TO IMPLEMENT IT_


* TODO KEYBINDINGS

** TODO PLAIN MAP
   Contains the most used commands, navigation and simple editing mostly.
** TODO SPC MAP
   Contains the most used commands which aren't related to navigation. 
   Put buffer saving, region evaluation, jumping etc here.
** TODO SPC c/, MAP
   Contains commands that are not used too often.

* TOOLS
  - phi-search
    https://github.com/zk-phi/phi-search
  - avy for fast navigation 
    works fine in modal mode
    https://github.com/abo-abo/avy
  - zones.el (?)
  https://www.emacswiki.org/emacs/Zones - persistent regions
* BOOKMARKS
  - https://github.com/clemera/objed
    - The expansion commands distinguish between block objects (objects built out of lines of text like paragraphs or text blocks with the same level of indentation and also comment blocks) and context objects (programming constructs like strings, brackets, comments or functions). This way you can quickly expand to the desired objects.


