* TASKS
** TODO make it more ergonomic
   - ban all single-hand command sequences, every complex command should use both hands _alternately_
   - don't bind (q a z p ; / [ ] ' shift ctrl) to minimize usage of pinkies
   - forget about mnemonics, it's not a problem with which-key
   - use _space_ as a mod-key

** TODO implement text objects
   - switching betwen text objects should be efficient and fast
   - there should be a dedicated key for entering text-object-mode for every type of text object.

** TODO find or write a better key engine
   - implement several navigation modes, including text object navigation

** TODO implement convinient isearch

** TODO get rid of annoying quirks
   - map russian characters
   - map capital charactes (?)
   - add more convinient bindings that exit modal state properly
   - all unused single-key presses are nil 
     
* IDEAS
  
** object manipulation 
   A sequence "special-key char" selects an object type when in modal mode, where _char_ is the first letter of text object name.

   Objects form a hierarchy, where char is the highest object and buffer is the lowest object

* TOOLS
  - https://www.emacswiki.org/emacs/Zones - persistent regions
* BOOKMARKS
  - https://github.com/clemera/objed
    - The expansion commands distinguish between block objects (objects built out of lines of text like paragraphs or text blocks with the same level of indentation and also comment blocks) and context objects (programming constructs like strings, brackets, comments or functions). This way you can quickly expand to the desired objects.


